apiVersion: v1
kind: ConfigMap
metadata:
  namespace: m
  name: spring-application-config
data:
  application.properties: |
    server.port=8000
    spring.data.mongodb.database=${MONGO_DATABASE}
    spring.data.mongodb.port=${MONGO_PORT}
    spring.data.mongodb.password=${MONGO_PASSWORD}
    spring.data.mongodb.username=${MONGO_USERNAME}
