  auth:
    rootPassword: "admin"
    username: "test"
    password: "12345"
    database: "otus"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 600m
      memory: 512Mi